source 'https://supermarket.chef.io'

cookbook 'enterprise', git: 'https://github.com/chef-cookbooks/enterprise-chef-common', branch: 'ma/update_runit'
cookbook 'chef-ha-drbd', path: './chef-ha-drbd'
cookbook 'private-chef', path: './private-chef'
cookbook 'runit', '> 1.6.0'
