source "https://rubygems.org"

gemspec

gem "chef_backup", git: "https://github.com/chef/chef_backup.git"
gem "omnibus-ctl", git: "https://github.com/chef/omnibus-ctl.git"
gem "veil", git: "https://github.com/chef/chef_secrets.git"
gem "toml" # for habitat-land

gem "chef", git: "https://github.com/chef/chef.git" # remove this once we have released chef 15
gem "ohai", git: "https://github.com/chef/ohai.git" # remove this once we have released chef 15
gem "license-acceptance", git: "https://github.com/chef/license-acceptance.git", glob: "components/ruby/*.gemspec"


