source "https://rubygems.org"

gemspec

gem "chef_backup", git: "https://github.com/chef/chef_backup.git"
gem "omnibus-ctl", git: "https://github.com/chef/omnibus-ctl.git"
gem "veil", git: "https://github.com/chef/chef_secrets.git"
gem "toml" # for habitat-land

gem "license-acceptance", git: "https://github.com/chef/license-acceptance.git", branch: "chef_server"


